# Generated by Django 2.0 on 2018-08-15 02:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('vendor', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sysdownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
                ('download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download', to='xxxt.download')),
            ],
        ),
    ]
