# Generated by Django 2.0 on 2018-08-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xxxt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysdownload',
            name='download',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sysdownload', to='xxxt.download'),
        ),
    ]
